# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
plugins:
  - jekyll-gist


# Site settings
title: Mike Chirico
email: mchirico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you're looking for information about me, you might want
  to check out my CV on <a href=https://stackoverflow.com/cv/mchirico>cv/mchirico.</a>
  Or, download <a href=https://storage.googleapis.com/montco-stats/monPub/mchirico_cw.pdf>mchiricoResume.pdf</a>
  <br>
  <a href='https://1drv.ms/w/s!AkYmehBMBDMdq3zfJBQTdN4srbQb'><img src='https://storage.googleapis.com/montco-stats/imagesUploaded/Screenshot2017-01-2417.33.06.png' width='63'></a>
  <br><br>
  You can also find me on <a href=https://www.kaggle.com/mchirico>Kaggle</a>

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mchirico.github.io/" # the base hostname & protocol for your site
twitter_username: mchirico
github_username:  mchirico

# Build settings


markdown: kramdown
highlighter: rouge

theme: minima

#excerpt_separator: <!--more-->
