title: Mike Chirico
author:
  name: Mike Chirico
  email: mchirico@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Go (Golang), Kubernetes, AWS, Argo Workflows, iOS/Swift development... that sort of thing.
  

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"
  skin: dark

kramdown:
  syntax_highlighter_opts:
    disable : true

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-coffeescript
 - jekyll-gist

